config/routes.rb
Rails.application.routes.draw do
  resources :tags
  devise_for :users, controllers: { registrations: 'registrations', :omniauth_callbacks => "omniauth_callbacks" }
  mount Bootsy::Engine => '/bootsy', as: 'bootsy'
  resources :debates
  resources :comments

  root 'debates#index'

  post 'rating/set_debate_rating' => 'ratings#set_debate_rating', as: 'set_debate_rating'
  post 'rating/set_comment_rating' => 'ratings#set_comment_rating', as: 'set_comment_rating'

end

app/models/debate.rb
class Debate < ActiveRecord::Base
	include Bootsy::Container

	belongs_to :user
	has_many :ratings
	has_many :comments
	has_many :debate_tags
	has_many :tags, through: :debate_tags

	mount_uploader :featured_image, AvatarUploader
end

app/controllers/debates_controller.rb
class DebatesController < ApplicationController
  before_action :set_debate, only: [:show, :edit, :update, :destroy]

  before_action :authenticate_user!, except: [:index, :show, :edit]

  load_and_authorize_resource

  # GET /debates
  # GET /debates.json
  def index
    @debates = Debate.all
  end

  # GET /debates/1
  # GET /debates/1.json
  def show
  end

  # GET /debates/new
  def new
    @debate = Debate.new
  end

  # GET /debates/1/edit
  def edit
  end

  # POST /debates
  # POST /debates.json
  def create
    params[:debate][:user_id] = current_user.id
    @debate = Debate.new(debate_params)

    respond_to do |format|
      if @debate.save
        # add tags after save debate
        params[:debate][:tags].each do |e|
          t = Tag.where(name: e).first
          if !t.nil?
            if !@debate.tags.include?(t)
              @debate.tags.push(t);
            end
          else
            @debate.tags.create(name: e) unless (e == '');
          end
        end
        format.html { redirect_to @debate, notice: 'Debate was successfully created.' }
        format.json { render :show, status: :created, location: @debate }
      else
        format.html { render :new }
        format.json { render json: @debate.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /debates/1
  # PATCH/PUT /debates/1.json
  def update
    params[:debate][:tags].each do |e|
      t = Tag.where(name: e).first
      if !t.nil?
        if !@debate.tags.include?(t)
          @debate.tags.push(t);
        end
      else
        @debate.tags.create(name: e);
      end
    end
    respond_to do |format|
      if @debate.update(debate_params)
        format.html { redirect_to @debate, notice: 'Debate was successfully updated.' }
        format.json { render :show, status: :ok, location: @debate }
      else
        format.html { render :edit }
        format.json { render json: @debate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /debates/1
  # DELETE /debates/1.json
  def destroy
    @debate.destroy
    respond_to do |format|
      format.html { redirect_to debates_url, notice: 'Debate was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    # Use callbacks to share common setup or constraints between actions.
    def set_debate
      @debate = Debate.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def debate_params
      params.require(:debate).permit(:title, :content, :featured_image, :user_id, :tags)
    end
end

app/helpers/debates_helper.rb
module DebatesHelper
end

app/views/debates/_form.html.erb
<%= form_for(@debate) do |f| %>
  <% if @debate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@debate.errors.count, "error") %> prohibited this debate from being saved:</h2>

      <ul>
      <% @debate.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :title %><br>
    <%= f.text_field :title %>
  </div>
  <div class="field">
    <%= f.label :content %><br>
    <%= f.bootsy_area :content, class: "form-control", rows: 15, cols: 10  %>
  </div>
  <div class="field">
    <%= f.label :featured_image %><br>
    <%= f.file_field :featured_image, multiple: false  %>
  </div>
  <div class="field">
    <% options_tag = [] %>
    <% Tag.all.each do |tag| %>
      <% options_tag.push [tag.name] %>
    <% end %>
    <%= f.label :tags %><br>
    <%= f.select(
      :tags,
      options_tag,
      { :prompt => "Please select Tag"},
      { :multiple => true}
    ) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/debates/edit.html.erb
<h1>Editing Debate</h1>

<%= render 'form' %>

<%= link_to 'Show', @debate %> |
<%= link_to 'Back', debates_path %>

app/views/debates/index.html.erb
<% @debates.each do |debate| %>
<article class="type-debate">
  <div class="row">
    <div class="col-md-12">
      <% if (!debate.featured_image.nil? && !debate.featured_image.url.nil?) %>
        <div class="featured_image col-md-3">
          <%= image_tag(debate.featured_image.url) %>
        </div>
        <div class="wrap-text col-md-9">
      <% else %>
        <div class="wrap-text col-md-12">
      <% end %>
        <div class="ratings">
          <span class="up text-success"><i class="fa fa-smile-o"></i><%= debate.ratings.where(up: true).count %></span>
          <span class="down text-danger"><i class="fa fa-frown-o"></i><%= debate.ratings.where(down: true).count %></span>
        </div>
        <div class="entry-meta">
          <%= "por #{(debate.user.name.nil?) ? debate.user.email : debate.user.name}" %>
          <% if debate.tags.size > 0 %>
            en 
            <%= debate.tags.map{|p| link_to p.name, p, class: 'tag-link' }.join(", ").html_safe %>
          <% end %>
          el
          <time><%= debate.created_at.strftime("%d-%m-%Y") %></time>
        </div>
        <h2>
          <%= link_to debate.title, debate  %>
        </h2>
        <p class="excerpt">
          <%= resumen( debate.content ) %>
        </p>
      </div><!-- .wrap-text -->
    </div>
</article>
<% end %>
<%= link_to 'New Debate', new_debate_path %>

app/views/debates/new.html.erb
<h1>New Debate</h1>

<%= render 'form' %>

<%= link_to 'Back', debates_path %>

app/views/debates/show.html.erb
<article class="single-debate">
	<p id="notice"><%= notice %></p>

	<div class="owner-actions">
		<%= link_to 'Edit', edit_debate_path(@debate) %>
		<%= link_to 'Back', debates_path %>
	</div>

	<div class="entry-header">
		<div class="entry-meta">
			<%= "por #{(@debate.user.name.nil?) ? @debate.user.email : @debate.user.name}" %>
      <% if @debate.tags.size > 0 %>
        en 
        <%= @debate.tags.map{|p| link_to p.name, p, class: 'tag-link' }.join(", ").html_safe %>
      <% end %>
      el
      <time><%= @debate.created_at.strftime("%d-%m-%Y") %></time>
		</div>
		<div class="entry-title">
			<h1><%= @debate.title %></h1>
			<div class="ratings">
				<% if current_user && Rating.where(debate_id: @debate.id, user_id: current_user.id).first.nil? %>
					<span class="up text-success">
						<%= link_to "<i class='fa fa-smile-o'></i>#{@debate.ratings.where(up: true).count}".html_safe, set_debate_rating_path(debate_id: @debate.id, up: true, down: false), remote: true, method: 'post', id: 'new_rating_up'  %>
					</span>
					<span class="down text-danger">
						<%= link_to "<i class='fa fa-frown-o'></i>#{@debate.ratings.where(down: true).count}".html_safe, set_debate_rating_path(debate_id: @debate.id, up: false, down: true), id: 'new_rating_down', remote: true, method: 'post' %>
					</span>
				<% else %>
					<span class="up text-success"><i class="fa fa-smile-o"></i><%= @debate.ratings.where(up: true).count %></span>
		      <span class="down text-danger"><i class="fa fa-frown-o"></i><%= @debate.ratings.where(down: true).count %></span>
				<% end %>
			</div>
		</div>
		<%= "<div class='featured-image'>#{image_tag(@debate.featured_image.url)}</div>".html_safe unless (@debate.featured_image.nil? || @debate.featured_image.url.nil?) %>
		<% if (!@debate.featured_image.nil? && !@debate.featured_image.url.nil?) %>
      <div class="featured_image">
        <%= image_tag(@debate.featured_image.url) %>
      </div>
    <% end %>
	</div>

	<div class="entry-content">
  	<%= @debate.content.html_safe %>
	</div>

<div id="comments">
	<div class="comment-list">
		<ul>
		<% Comment.where(debate_id: @debate.id).each do |comment| %>
			<% @comment = comment %>
			<%= render "comments/comment" %>
			<% @comment = nil %>
		<% end %>
		</ul>
	</div>
	<%= render 'comments/response' %>
</div>
</article>